# Generated by Django 3.2.13 on 2022-06-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Blog post subheader', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Joko Like blog post', max_length=255),
        ),
    ]
